Numpy

In [1]:
import numpy as np

array = np.random.randn(2,3)

In [2]:
array

array([[ 0.53936593, -2.98302432,  1.63802976],
       [ 1.81687974,  1.57895246, -1.07494577]])

In [3]:
array*2

array([[ 1.07873187, -5.96604864,  3.27605951],
       [ 3.63375949,  3.15790491, -2.14989153]])

In [4]:
array + array

array([[ 1.07873187, -5.96604864,  3.27605951],
       [ 3.63375949,  3.15790491, -2.14989153]])

In [5]:
array.shape

(2, 3)

In [6]:
array.dtype

dtype('float64')

In [8]:
a=[[1,2,3,4],[5,6,7,8]]

In [9]:
data = np.array(a)

In [10]:
data.ndim


2

In [11]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

It's not safe to assume that np.empty function will return an array of all zeros, 
it may return uninitialized 'garbage' values

In [13]:
np.empty((2,3,3))

array([[[1.24080832e-316, 0.00000000e+000, 6.93728444e-310],
        [6.93728445e-310, 6.93728444e-310, 6.93728444e-310],
        [6.93728443e-310, 6.93728444e-310, 6.93728429e-310]],

       [[6.93728371e-310, 6.93728381e-310, 3.21142670e-322],
        [6.93728509e-310, 6.93728509e-310, 6.93728381e-310],
        [6.93728381e-310, 6.93728381e-310, 1.46923442e+195]]])

array of strings representing numbers , you can user astype to convert them into numberic form.

In [17]:
data = np.array(['2.0','3.3333'],dtype=np.string_)

In [18]:
data.dtype

dtype('S6')

In [24]:
data.astype(np.float16
           )

array([2.   , 3.334], dtype=float16)

Vectorization : express batch operations on data without any for loops


In [30]:
arr = np.array([[1,2,3],[4,5,6] ], dtype =np.float)

In [31]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [34]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [35]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [38]:
arr2 = np.array([[4,0,1],[7,12,5]])

In [39]:
arr > arr2

array([[False,  True,  True],
       [False, False,  True]])

In [40]:
arr2d=np.array([[1,2,3,4],[5,6,7,8
                          ]])

In [42]:
arr2d[1]

array([5, 6, 7, 8])

In [43]:
arr2d[1,1]

6

In [44]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [46]:
arr3d.shape


(2, 2, 3)

In [47]:
arr3d[1]


array([[ 7,  8,  9],
       [10, 11, 12]])

In [49]:
arr3d[1,0]

array([7, 8, 9])

In [50]:
arr3d[1,0].shape

(3,)

Boolean Indexing

In [64]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [72]:
data = np.random.randn(7,4)

TypeError: randn() got an unexpected keyword argument 'seed'

In [53]:
names


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [54]:
data

array([[ 0.06631848,  0.61608853,  1.23945991,  0.80632329],
       [ 0.13795859,  0.44154574, -0.61583181,  1.55579163],
       [ 1.22318754, -1.3221846 , -0.83304805,  0.82644408],
       [ 0.13512362,  1.7761183 ,  0.1658922 , -0.28061259],
       [-0.23237091,  2.34924691,  0.03651564, -1.09743097],
       [ 0.66420203,  0.58992835,  0.84507579,  1.16586551],
       [ 0.05620423,  0.13244687, -0.29320951,  0.62690268]])

In [55]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [63]:
data[names=='Bob']

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 7

In [67]:
mask = (names=='Bob') | (names=='Will')

In [70]:
data[mask]

array([[-0.68110928, -1.49005475,  1.23417993, -0.70289381],
       [ 0.80840286, -0.05153726,  1.60658131, -0.51384537],
       [ 0.46661813, -1.1722164 , -0.78291721,  0.28180473],
       [ 0.38955473,  0.20162388, -0.88753786, -0.09282693]])

In [73]:
data


array([[-0.68110928, -1.49005475,  1.23417993, -0.70289381],
       [ 0.87297874,  0.78722408,  0.23832936, -0.0950411 ],
       [ 0.80840286, -0.05153726,  1.60658131, -0.51384537],
       [ 0.46661813, -1.1722164 , -0.78291721,  0.28180473],
       [ 0.38955473,  0.20162388, -0.88753786, -0.09282693],
       [-0.17680317, -0.65112725, -0.37850763,  1.06001001],
       [-0.4414147 ,  2.36557922, -1.58323558,  0.95454957]])

In [74]:
data[data<0] =0

In [75]:
data

array([[0.        , 0.        , 1.23417993, 0.        ],
       [0.87297874, 0.78722408, 0.23832936, 0.        ],
       [0.80840286, 0.        , 1.60658131, 0.        ],
       [0.46661813, 0.        , 0.        , 0.28180473],
       [0.38955473, 0.20162388, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.06001001],
       [0.        , 2.36557922, 0.        , 0.95454957]])

Fancy Indexing

In [80]:
arr = np.empty((7,5))
arr


TypeError: data type not understood

In [82]:
for i in range(7):
    arr[i] = i
arr

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.]])

In [83]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4., 4.],
       [3., 3., 3., 3., 3.],
       [0., 0., 0., 0., 0.],
       [6., 6., 6., 6., 6.]])

In [85]:
arr[[-3,-4,-7,-1]]

array([[4., 4., 4., 4., 4.],
       [3., 3., 3., 3., 3.],
       [0., 0., 0., 0., 0.],
       [6., 6., 6., 6., 6.]])

In [86]:
arr = np.arange(32).reshape((8, 4))

In [87]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [88]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [89]:
arr[[1,5,7,2],[0,3,2,1]]

array([ 4, 23, 30,  9])

Keep in mand that fancy indexing ,unlike slicing, always copies values into a new array

Transposing Arrays  and Swapping Axes

In [91]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [92]:
arr.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

<ipython-input-95-3aac3c9a7ed6>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  arr == arr.T


False

In [97]:
arr = np.random.randn(6,3)
arr

array([[-0.37090472, -1.11061704, -0.16383443],
       [ 2.50158691, -1.82513588,  0.97868566],
       [-0.41728276, -0.44604873, -0.72432618],
       [ 1.26302646,  1.12250786, -0.33982648],
       [ 0.57634505,  0.41065439, -0.3386835 ],
       [-0.37233389,  1.89877372,  1.31573513]])

In [98]:
np.dot(arr.T ,arr)

array([[ 8.63567426, -3.02021651,  1.69698185],
       [-3.02021651,  9.79755321,  0.69655129],
       [ 1.69698185,  0.69655129,  3.47066322]])

In [99]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [100]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [101]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [102]:
array = np.random.randn(7) *6
array

array([ 7.7543899 ,  6.8846467 , -5.24341102, -5.84076604,  1.36178374,
       -2.82620699, -4.84036379])

In [103]:
remainder, whole_part =  np.modf(array)

In [105]:
remainder

array([ 0.7543899 ,  0.8846467 , -0.24341102, -0.84076604,  0.36178374,
       -0.82620699, -0.84036379])

In [106]:
whole_part

array([ 7.,  6., -5., -5.,  1., -2., -4.])

In [107]:
np.sqrt(array)

<ipython-input-107-48638f89c3ab>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(array)


array([2.78467052, 2.62386103,        nan,        nan, 1.1669549 ,
              nan,        nan])

In [108]:
array

array([ 7.7543899 ,  6.8846467 , -5.24341102, -5.84076604,  1.36178374,
       -2.82620699, -4.84036379])

In [109]:
np.sqrt(array,array)

<ipython-input-109-f41e6dd97513>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(array,array)


array([2.78467052, 2.62386103,        nan,        nan, 1.1669549 ,
              nan,        nan])

In [110]:
array

array([2.78467052, 2.62386103,        nan,        nan, 1.1669549 ,
              nan,        nan])

Array-Oriented Programming

In [135]:
points = np.arange(-5,5,1)
points

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [141]:
points2 = np.arange(0,10,1)
points2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
xs, ys = np.meshgrid(points, points2)

In [143]:
xs

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [144]:
ys

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [127]:
z=  np.sqrt(xs**2+ys**2)

In [128]:
z

array([[25.49509757, 25.39517828, 25.29545888, ..., 25.19593937,
        25.29545888, 25.39517828],
       [25.49509757, 25.39517828, 25.29545888, ..., 25.19593937,
        25.29545888, 25.39517828],
       [25.49509757, 25.39517828, 25.29545888, ..., 25.19593937,
        25.29545888, 25.39517828],
       ...,
       [25.49509757, 25.39517828, 25.29545888, ..., 25.19593937,
        25.29545888, 25.39517828],
       [25.49509757, 25.39517828, 25.29545888, ..., 25.19593937,
        25.29545888, 25.39517828],
       [25.49509757, 25.39517828, 25.29545888, ..., 25.19593937,
        25.29545888, 25.39517828]])

Expressing conditional Logic as array operations

In [151]:
xarr = np.array([1,2,3,4,5])
yarr =np.array( [6,7,8,9,0])

In [146]:
cond = [True,False, True,True,False]

In [152]:
np.where (cond,xarr, yarr)

array([1, 7, 3, 4, 0])

In [153]:
np.where (xarr > 2,xarr, 0)

array([0, 0, 3, 4, 5])

In [154]:
np.where (xarr > 2,xarr, yarr)

array([6, 7, 3, 4, 5])

Mathematical and Statistic Method

In [155]:
arr = np.arange(15).reshape(3,5)

In [156]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [157]:
np.sum(arr)

105

In [158]:
np.sum(arr, axis=0) ##compute sum down the rows

array([15, 18, 21, 24, 27])

In [159]:
np.sum(arr, axis=1) # compute sum across the columns

array([10, 35, 60])

In [163]:
arr.cumsum(axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [174]:
arr = np.array([2, 3,4])

In [169]:
arr.cumsum()  

array([1, 3, 6])

In [175]:
arr.prod() # 连乘

24

In [181]:
from numpy.linalg import inv, qr,det

In [177]:
X = np.random.randn(5, 5)

In [178]:
X

array([[-0.34845927, -1.30361793, -1.606256  ,  1.36751315,  0.66010501],
       [-0.75335542,  0.37299195,  0.47671129, -1.14304566, -1.0316198 ],
       [ 0.48043306,  1.53522852, -0.13227565,  0.43534105, -0.2064048 ],
       [-0.58127818,  0.14470413, -1.96749339, -0.61772024, -0.24875295],
       [ 0.52287008, -0.61288963,  0.78223907, -1.17545231, -1.32303997]])

In [179]:
mat = X.T.dot(X)
mat

array([[ 1.53106162,  0.50626178,  1.68970255,  0.33820769, -0.09919039],
       [ 0.50626178,  4.5920423 ,  1.30454961, -0.90967764, -0.78730725],
       [ 1.68970255,  1.30454961,  7.30773704, -2.50318823, -2.0702939 ],
       [ 0.33820769, -0.90967764, -2.50318823,  5.12943385,  3.70086446],
       [-0.09919039, -0.78730725, -2.0702939 ,  3.70086446,  3.35489377]])

In [183]:
inv(X)

array([[-0.28485495, -0.90353237,  0.15815156,  0.20171106,  0.4997946 ],
       [-0.21024642,  0.09174404,  0.34611543,  0.07349501, -0.24424937],
       [-0.06751207,  0.22072821, -0.11254052, -0.43445958, -0.10655055],
       [ 0.71005778,  0.43136951,  0.55572519, -0.50232909,  0.02566428],
       [-0.68594595, -0.65232426, -0.6581055 ,  0.23509265, -0.53096627]])

In [182]:
det(X)

8.627788876669628

In [184]:
np.random.seed(1234)

In [189]:
np.random.randn(5,5)

array([[ 2.00784295,  0.22696254, -1.15265911,  0.63197945,  0.03951269],
       [ 0.46439233, -3.56351666,  1.32110562,  0.15263055,  0.16452954],
       [-0.43009569,  0.76736874,  0.98491984,  0.27083585,  1.39198619],
       [ 0.07984231, -0.39996458, -1.02785056, -0.58471821,  0.81659393],
       [-0.08194705, -0.34476601,  0.52828815, -1.06898878, -0.51188131]])

Simulating many random walks at once

In [194]:
step = 500

In [203]:
n = 100

In [204]:
draw = np.random.randint(0,2, size=[n, step]) # 0 ro 1

In [205]:
walks = np.where(draw > 0 ,1,-1)

In [206]:
walks

array([[-1, -1,  1, ..., -1,  1, -1],
       [-1,  1,  1, ...,  1,  1,  1],
       [ 1, -1,  1, ...,  1,  1,  1],
       ...,
       [-1, -1, -1, ...,  1, -1,  1],
       [-1,  1, -1, ..., -1,  1,  1],
       [-1,  1, -1, ...,  1,  1,  1]])

In [207]:
cum_walks = walks.cumsum(axis=1)

In [208]:
cum_walks

array([[ -1,  -2,  -1, ..., -24, -23, -24],
       [ -1,   0,   1, ...,  22,  23,  24],
       [  1,   0,   1, ...,  26,  27,  28],
       ...,
       [ -1,  -2,  -3, ..., -16, -17, -16],
       [ -1,   0,  -1, ...,   4,   5,   6],
       [ -1,   0,  -1, ...,  22,  23,  24]])

In [209]:
cum_walks.max()

53

In [210]:
cum_walks.min()

-56

In [211]:
np.abs(cum_walks) >=30

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

array([False,  True,  True, False, False,  True, False, False,  True,
       False,  True, False,  True,  True,  True, False,  True, False,
        True, False, False, False, False,  True, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False,  True,  True,  True, False,
       False,  True,  True, False,  True, False,  True,  True,  True,
       False,  True,  True, False,  True, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
        True,  True, False, False, False, False,  True,  True,  True,
       False, False, False, False, False,  True, False, False, False,
       False,  True,  True, False,  True,  True,  True, False, False,
       False])

In [214]:
hits30 =(np.abs(cum_walks) >=30 ).any(1)

In [215]:
hits30.sum()

39

In [217]:
np.abs(walks[hits30]) >= 30

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [226]:
(np.abs(cum_walks[hits30]) >= 30)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ...,  True,  True,  True],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ...,  True,  True,  True],
       [False, False, False, ...,  True,  True,  True]])

In [224]:
crossing_times = (np.abs(cum_walks[hits30]) >= 30).argmax(1)

argmax :return the first index of the maximum value .
        In boolean array , the maximum value is True.

In [225]:
crossing_times

array([231, 209, 259, 103, 437, 201, 203, 271, 395, 255, 241, 279, 463,
       165, 379,  83, 245, 261, 237, 481, 175, 299, 253, 169, 331, 283,
       347,  63, 143, 391, 325, 327, 217, 371, 447, 391, 469, 233, 243])